/* AUTO-GENERATED by tools/gen_tz_table.py -- do not edit.
 * Source: IANA tzdata via /usr/share/zoneinfo
 * Regenerate when tzdata changes; see the script header. */
#ifndef TZ_TABLE_H
#define TZ_TABLE_H

#include <stdint.h>

#define TZ_NZONES   407
#define TZ_NRULES   88
#define TZ_NREGIONS 9

/* POSIX TZ rule strings, deduplicated across zones. */
static const char *const tz_rule_str[TZ_NRULES] = {
    "<+00>0<+01>,0/0,J365/25",
    "<+00>0<+02>-2,M3.5.0/1,M10.5.0/3",
    "<+0330>-3:30",
    "<+03>-3",
    "<+0430>-4:30",
    "<+04>-4",
    "<+0530>-5:30",
    "<+0545>-5:45",
    "<+05>-5",
    "<+0630>-6:30",
    "<+06>-6",
    "<+07>-7",
    "<+0845>-8:45",
    "<+08>-8",
    "<+09>-9",
    "<+1030>-10:30<+11>-11,M10.1.0,M4.1.0",
    "<+10>-10",
    "<+11>-11",
    "<+11>-11<+12>,M10.1.0,M4.1.0/3",
    "<+1245>-12:45<+1345>,M9.5.0/2:45,M4.1.0/3:45",
    "<+12>-12",
    "<+13>-13",
    "<+14>-14",
    "<-01>1",
    "<-01>1<+00>,M3.5.0/0,M10.5.0/1",
    "<-02>2",
    "<-02>2<-01>,M3.5.0/-1,M10.5.0/0",
    "<-03>3",
    "<-03>3<-02>,M3.2.0,M11.1.0",
    "<-04>4",
    "<-04>4<-03>,M9.1.6/24,M4.1.6/24",
    "<-05>5",
    "<-06>6",
    "<-06>6<-05>,M9.1.6/22,M4.1.6/22",
    "<-08>8",
    "<-0930>9:30",
    "<-09>9",
    "<-10>10",
    "<-11>11",
    "ACST-9:30",
    "ACST-9:30ACDT,M10.1.0,M4.1.0/3",
    "AEST-10",
    "AEST-10AEDT,M10.1.0,M4.1.0/3",
    "AKST9AKDT,M3.2.0,M11.1.0",
    "AST4",
    "AST4ADT,M3.2.0,M11.1.0",
    "AWST-8",
    "CAT-2",
    "CET-1",
    "CET-1CEST,M3.5.0,M10.5.0/3",
    "CST-8",
    "CST5CDT,M3.2.0/0,M11.1.0/1",
    "CST6",
    "CST6CDT,M3.2.0,M11.1.0",
    "ChST-10",
    "EAT-3",
    "EET-2",
    "EET-2EEST,M3.4.4/50,M10.4.4/50",
    "EET-2EEST,M3.5.0/0,M10.5.0/0",
    "EET-2EEST,M3.5.0/3,M10.5.0/4",
    "EET-2EEST,M4.5.5/0,M10.5.4/24",
    "EST5",
    "EST5EDT,M3.2.0,M11.1.0",
    "GMT0",
    "GMT0BST,M3.5.0/1,M10.5.0",
    "GMT0IST,M3.5.0/1,M10.5.0",
    "HKT-8",
    "HST10",
    "HST10HDT,M3.2.0,M11.1.0",
    "IST-2IDT,M3.4.4/26,M10.5.0",
    "IST-5:30",
    "JST-9",
    "KST-9",
    "MSK-3",
    "MST7",
    "MST7MDT,M3.2.0,M11.1.0",
    "NST3:30NDT,M3.2.0,M11.1.0",
    "NZST-12NZDT,M9.5.0,M4.1.0/3",
    "PKT-5",
    "PST-8",
    "PST8PDT,M3.2.0,M11.1.0",
    "SAST-2",
    "SST11",
    "WAT-1",
    "WET0WEST,M3.5.0/1,M10.5.0",
    "WIB-7",
    "WIT-9",
    "WITA-8",
};

static const char *const tz_region_str[TZ_NREGIONS] = {
    "Africa",
    "America",
    "Antarctica",
    "Asia",
    "Atlantic",
    "Australia",
    "Europe",
    "Indian",
    "Pacific",
};

/* City names, NUL-separated, sorted case-insensitively. */
static const char tz_city_blob[] =
    "Abidjan\0""Accra\0""Adak\0""Addis_Ababa\0""Adelaide\0""Aden\0"
    "Algiers\0""Almaty\0""Amman\0""Amsterdam\0""Anadyr\0""Anchorage\0"
    "Andorra\0""Anguilla\0""Antananarivo\0""Antigua\0""Apia\0""Aqtau\0"
    "Aqtobe\0""Araguaina\0""Aruba\0""Ashgabat\0""Asmara\0""Astrakhan\0"
    "Asuncion\0""Athens\0""Atikokan\0""Atyrau\0""Auckland\0""Azores\0"
    "Baghdad\0""Bahia\0""Bahia_Banderas\0""Bahrain\0""Baku\0""Bamako\0"
    "Bangkok\0""Bangui\0""Banjul\0""Barbados\0""Barnaul\0""Beirut\0"
    "Belem\0""Belgrade\0""Belize\0""Berlin\0""Bermuda\0""Beulah\0"
    "Bishkek\0""Bissau\0""Blanc-Sablon\0""Blantyre\0""Boa_Vista\0""Bogota\0"
    "Boise\0""Bougainville\0""Brazzaville\0""Brisbane\0""Broken_Hill\0"
    "Brunei\0""Brussels\0""Bucharest\0""Budapest\0""Buenos_Aires\0"
    "Bujumbura\0""Cairo\0""Cambridge_Bay\0""Campo_Grande\0""Canary\0"
    "Cancun\0""Cape_Verde\0""Caracas\0""Casablanca\0""Casey\0""Catamarca\0"
    "Cayenne\0""Cayman\0""Center\0""Ceuta\0""Chagos\0""Chatham\0""Chicago\0"
    "Chihuahua\0""Chisinau\0""Chita\0""Christmas\0""Chuuk\0"
    "Ciudad_Juarez\0""Cocos\0""Colombo\0""Comoro\0""Conakry\0""Copenhagen\0"
    "Cordoba\0""Costa_Rica\0""Coyhaique\0""Creston\0""Cuiaba\0""Curacao\0"
    "Dakar\0""Damascus\0""Danmarkshavn\0""Dar_es_Salaam\0""Darwin\0"
    "Davis\0""Dawson\0""Dawson_Creek\0""Denver\0""Detroit\0""Dhaka\0"
    "Dili\0""Djibouti\0""Dominica\0""Douala\0""Dubai\0""Dublin\0"
    "DumontDUrville\0""Dushanbe\0""Easter\0""Edmonton\0""Efate\0"
    "Eirunepe\0""El_Aaiun\0""El_Salvador\0""Eucla\0""Fakaofo\0""Famagusta\0"
    "Faroe\0""Fiji\0""Fort_Nelson\0""Fortaleza\0""Freetown\0""Funafuti\0"
    "Gaborone\0""Galapagos\0""Gambier\0""Gaza\0""Gibraltar\0""Glace_Bay\0"
    "Goose_Bay\0""Grand_Turk\0""Grenada\0""Guadalcanal\0""Guadeloupe\0"
    "Guam\0""Guatemala\0""Guayaquil\0""Guernsey\0""Guyana\0""Halifax\0"
    "Harare\0""Havana\0""Hebron\0""Helsinki\0""Hermosillo\0""Ho_Chi_Minh\0"
    "Hobart\0""Hong_Kong\0""Honolulu\0""Hovd\0""Indianapolis\0""Inuvik\0"
    "Iqaluit\0""Irkutsk\0""Isle_of_Man\0""Istanbul\0""Jakarta\0""Jamaica\0"
    "Jayapura\0""Jersey\0""Jerusalem\0""Johannesburg\0""Juba\0""Jujuy\0"
    "Juneau\0""Kabul\0""Kaliningrad\0""Kamchatka\0""Kampala\0""Kanton\0"
    "Karachi\0""Kathmandu\0""Kerguelen\0""Khandyga\0""Khartoum\0""Kigali\0"
    "Kinshasa\0""Kiritimati\0""Kirov\0""Knox\0""Kolkata\0""Kosrae\0"
    "Krasnoyarsk\0""Kuala_Lumpur\0""Kuching\0""Kuwait\0""Kwajalein\0"
    "Kyiv\0""La_Paz\0""La_Rioja\0""Lagos\0""Libreville\0""Lima\0"
    "Lindeman\0""Lisbon\0""Ljubljana\0""Lome\0""London\0""Lord_Howe\0"
    "Los_Angeles\0""Louisville\0""Luanda\0""Lubumbashi\0""Lusaka\0"
    "Luxembourg\0""Macau\0""Maceio\0""Macquarie\0""Madeira\0""Madrid\0"
    "Magadan\0""Mahe\0""Majuro\0""Makassar\0""Malabo\0""Maldives\0""Malta\0"
    "Managua\0""Manaus\0""Manila\0""Maputo\0""Marengo\0""Marquesas\0"
    "Martinique\0""Maseru\0""Matamoros\0""Mauritius\0""Mawson\0""Mayotte\0"
    "Mazatlan\0""Mbabane\0""McMurdo\0""Melbourne\0""Mendoza\0""Menominee\0"
    "Merida\0""Metlakatla\0""Mexico_City\0""Midway\0""Minsk\0""Miquelon\0"
    "Mogadishu\0""Monaco\0""Moncton\0""Monrovia\0""Monterrey\0"
    "Montevideo\0""Monticello\0""Montserrat\0""Moscow\0""Muscat\0"
    "Nairobi\0""Nassau\0""Nauru\0""Ndjamena\0""New_Salem\0""New_York\0"
    "Niamey\0""Nicosia\0""Niue\0""Nome\0""Norfolk\0""Noronha\0"
    "Nouakchott\0""Noumea\0""Novokuznetsk\0""Novosibirsk\0""Nuuk\0"
    "Ojinaga\0""Omsk\0""Oral\0""Oslo\0""Ouagadougou\0""Pago_Pago\0""Palau\0"
    "Palmer\0""Panama\0""Paramaribo\0""Paris\0""Perth\0""Petersburg\0"
    "Phnom_Penh\0""Phoenix\0""Pitcairn\0""Pohnpei\0""Pontianak\0"
    "Port-au-Prince\0""Port_Moresby\0""Port_of_Spain\0""Porto-Novo\0"
    "Porto_Velho\0""Prague\0""Puerto_Rico\0""Punta_Arenas\0""Pyongyang\0"
    "Qatar\0""Qostanay\0""Qyzylorda\0""Rankin_Inlet\0""Rarotonga\0"
    "Recife\0""Regina\0""Resolute\0""Reunion\0""Reykjavik\0""Riga\0"
    "Rio_Branco\0""Rio_Gallegos\0""Riyadh\0""Rome\0""Rothera\0""Saipan\0"
    "Sakhalin\0""Salta\0""Samara\0""Samarkand\0""San_Juan\0""San_Luis\0"
    "Santarem\0""Santiago\0""Santo_Domingo\0""Sao_Paulo\0""Sao_Tome\0"
    "Sarajevo\0""Saratov\0""Scoresbysund\0""Seoul\0""Shanghai\0"
    "Simferopol\0""Singapore\0""Sitka\0""Skopje\0""Sofia\0""South_Georgia\0"
    "Srednekolymsk\0""St_Helena\0""St_Johns\0""St_Kitts\0""St_Lucia\0"
    "St_Thomas\0""St_Vincent\0""Stanley\0""Stockholm\0""Swift_Current\0"
    "Sydney\0""Syowa\0""Tahiti\0""Taipei\0""Tallinn\0""Tarawa\0""Tashkent\0"
    "Tbilisi\0""Tegucigalpa\0""Tehran\0""Tell_City\0""Thimphu\0""Thule\0"
    "Tijuana\0""Tirane\0""Tokyo\0""Tomsk\0""Tongatapu\0""Toronto\0"
    "Tortola\0""Tripoli\0""Troll\0""Tucuman\0""Tunis\0""Ulaanbaatar\0"
    "Ulyanovsk\0""Urumqi\0""Ushuaia\0""Ust-Nera\0""Vaduz\0""Vancouver\0"
    "Vevay\0""Vienna\0""Vientiane\0""Vilnius\0""Vincennes\0""Vladivostok\0"
    "Volgograd\0""Vostok\0""Wake\0""Wallis\0""Warsaw\0""Whitehorse\0"
    "Winamac\0""Windhoek\0""Winnipeg\0""Yakutat\0""Yakutsk\0""Yangon\0"
    "Yekaterinburg\0""Yerevan\0""Zagreb\0""Zurich\0"
;

static const uint16_t tz_city_off[TZ_NZONES] = {
        0,    8,   14,   19,   31,   40,   45,   53,   60,   66,   76,   83,
       93,  101,  110,  123,  131,  136,  142,  149,  159,  165,  174,  181,
      191,  200,  207,  216,  223,  232,  239,  247,  253,  268,  276,  281,
      288,  296,  303,  310,  319,  327,  334,  340,  349,  356,  363,  371,
      378,  386,  393,  406,  415,  425,  432,  438,  451,  463,  472,  484,
      491,  500,  510,  519,  532,  542,  548,  562,  575,  582,  589,  600,
      608,  619,  625,  635,  643,  650,  657,  663,  670,  678,  686,  696,
      705,  711,  721,  727,  741,  747,  755,  762,  770,  781,  789,  800,
      810,  818,  825,  833,  839,  848,  861,  875,  882,  888,  895,  908,
      915,  923,  929,  934,  943,  952,  959,  965,  972,  987,  996, 1003,
     1012, 1018, 1027, 1036, 1048, 1054, 1062, 1072, 1078, 1083, 1095, 1105,
     1114, 1123, 1132, 1142, 1150, 1155, 1165, 1175, 1185, 1196, 1204, 1216,
     1227, 1232, 1242, 1252, 1261, 1268, 1276, 1283, 1290, 1297, 1306, 1317,
     1329, 1336, 1346, 1355, 1360, 1373, 1380, 1388, 1396, 1408, 1417, 1425,
     1433, 1442, 1449, 1459, 1472, 1477, 1483, 1490, 1496, 1508, 1518, 1526,
     1533, 1541, 1551, 1561, 1570, 1579, 1586, 1595, 1606, 1612, 1617, 1625,
     1632, 1644, 1657, 1665, 1672, 1682, 1687, 1694, 1703, 1709, 1720, 1725,
     1734, 1741, 1751, 1756, 1763, 1773, 1785, 1796, 1803, 1814, 1821, 1832,
     1838, 1845, 1855, 1863, 1870, 1878, 1883, 1890, 1899, 1906, 1915, 1921,
     1929, 1936, 1943, 1950, 1958, 1968, 1979, 1986, 1996, 2006, 2013, 2021,
     2030, 2038, 2046, 2056, 2064, 2074, 2081, 2092, 2104, 2111, 2117, 2126,
     2136, 2143, 2151, 2160, 2170, 2181, 2192, 2203, 2210, 2217, 2225, 2232,
     2238, 2247, 2257, 2266, 2273, 2281, 2286, 2291, 2299, 2307, 2318, 2325,
     2338, 2350, 2355, 2363, 2368, 2373, 2378, 2390, 2400, 2406, 2413, 2420,
     2431, 2437, 2443, 2454, 2465, 2473, 2482, 2490, 2500, 2515, 2528, 2542,
     2553, 2565, 2572, 2584, 2597, 2607, 2613, 2622, 2632, 2645, 2655, 2662,
     2669, 2678, 2686, 2696, 2701, 2712, 2725, 2732, 2737, 2745, 2752, 2761,
     2767, 2774, 2784, 2793, 2802, 2811, 2820, 2834, 2844, 2853, 2862, 2870,
     2883, 2889, 2898, 2909, 2919, 2925, 2932, 2938, 2952, 2966, 2976, 2985,
     2994, 3003, 3013, 3024, 3032, 3042, 3056, 3063, 3069, 3076, 3083, 3091,
     3098, 3107, 3115, 3127, 3134, 3144, 3152, 3158, 3166, 3173, 3179, 3185,
     3195, 3203, 3211, 3219, 3225, 3233, 3239, 3251, 3261, 3268, 3276, 3285,
     3291, 3301, 3307, 3314, 3324, 3332, 3342, 3354, 3364, 3371, 3376, 3383,
     3390, 3401, 3409, 3418, 3427, 3435, 3443, 3450, 3464, 3472, 3479,
};

static const uint8_t tz_zone_region[TZ_NZONES] = {
      0,  0,  1,  0,  5,  3,  0,  3,  3,  6,  3,  1,  6,  1,  7,  1,  8,  3,  3,  1,
      1,  3,  0,  6,  1,  6,  1,  3,  8,  4,  3,  1,  1,  3,  3,  0,  3,  0,  0,  1,
      3,  3,  1,  6,  1,  6,  4,  1,  3,  0,  1,  0,  1,  1,  1,  8,  0,  5,  5,  3,
      6,  6,  6,  1,  0,  0,  1,  1,  4,  1,  4,  1,  0,  2,  1,  1,  1,  1,  0,  7,
      8,  1,  1,  6,  3,  7,  8,  1,  7,  3,  7,  0,  6,  1,  1,  1,  1,  1,  1,  0,
      3,  1,  0,  5,  2,  1,  1,  1,  1,  3,  3,  0,  1,  0,  3,  6,  2,  3,  8,  1,
      8,  1,  0,  1,  5,  8,  3,  4,  8,  1,  1,  0,  8,  0,  8,  8,  3,  6,  1,  1,
      1,  1,  8,  1,  8,  1,  1,  6,  1,  1,  0,  1,  3,  6,  1,  3,  5,  3,  8,  3,
      1,  1,  1,  3,  6,  6,  3,  1,  3,  6,  3,  0,  0,  1,  1,  3,  6,  3,  0,  8,
      3,  3,  7,  3,  0,  0,  0,  8,  6,  1,  3,  8,  3,  3,  3,  3,  8,  6,  1,  1,
      0,  0,  1,  5,  6,  6,  0,  6,  5,  1,  1,  0,  0,  0,  6,  3,  1,  2,  4,  6,
      3,  7,  8,  3,  0,  7,  6,  1,  1,  3,  0,  1,  8,  1,  0,  1,  7,  2,  7,  1,
      0,  2,  5,  1,  1,  1,  1,  1,  8,  6,  1,  0,  6,  1,  0,  1,  1,  1,  1,  6,
      3,  0,  1,  8,  0,  1,  1,  0,  3,  8,  1,  8,  1,  0,  8,  3,  3,  1,  1,  3,
      3,  6,  0,  8,  8,  2,  1,  1,  6,  5,  1,  3,  1,  8,  8,  3,  1,  8,  1,  0,
      1,  6,  1,  1,  3,  3,  3,  3,  1,  8,  1,  1,  1,  7,  4,  6,  1,  1,  3,  6,
      2,  8,  3,  1,  6,  3,  1,  1,  1,  1,  1,  1,  0,  6,  6,  1,  3,  3,  6,  3,
      1,  6,  6,  4,  3,  4,  1,  1,  1,  1,  1,  4,  6,  1,  5,  2,  8,  3,  6,  8,
      3,  3,  1,  3,  1,  3,  1,  1,  6,  3,  3,  8,  1,  1,  0,  2,  1,  0,  3,  6,
      3,  1,  3,  6,  1,  1,  6,  3,  6,  1,  3,  6,  2,  8,  8,  6,  1,  1,  0,  1,
      1,  3,  3,  3,  3,  6,  6,
};

static const uint8_t tz_zone_rule[TZ_NZONES] = {
     63, 63, 68, 55, 40,  3, 48,  8,  3, 49, 20, 43, 49, 44, 55, 44, 21,  8,  8, 27,
     44,  8, 55,  5, 27, 59, 61,  8, 77, 24,  3, 27, 52,  3,  5, 63, 11, 83, 63, 44,
     11, 58, 27, 49, 52, 49, 45, 53, 10, 63, 44, 47, 29, 31, 75, 17, 83, 41, 40, 13,
     49, 59, 49, 27, 47, 60, 75, 29, 84, 61, 23, 29,  0, 13, 27, 27, 61, 53, 49, 10,
     19, 53, 52, 59, 14, 11, 16, 75,  9,  6, 55, 63, 49, 27, 52, 27, 74, 29, 44, 63,
      3, 63, 55, 39, 11, 74, 74, 75, 62, 10, 14, 55, 44, 83,  5, 65, 16,  8, 33, 75,
     17, 31,  0, 52, 12, 21, 59, 84, 20, 74, 27, 63, 20, 47, 32, 36, 57, 49, 45, 45,
     62, 44, 17, 44, 54, 52, 31, 64, 29, 45, 47, 51, 57, 59, 74, 11, 42, 66, 67, 11,
     62, 75, 62, 13, 64,  3, 85, 61, 86, 64, 69, 81, 47, 27, 43,  4, 56, 20, 55, 21,
     78,  7,  8, 14, 47, 47, 83, 22, 73, 53, 70, 17, 11, 13, 13,  3, 20, 59, 29, 27,
     83, 83, 31, 41, 84, 49, 63, 64, 15, 80, 62, 83, 47, 47, 49, 50, 27, 42, 84, 49,
     17,  5, 20, 87, 83,  8, 49, 52, 29, 79, 47, 62, 35, 44, 81, 53,  5,  8, 55, 74,
     81, 77, 42, 27, 53, 52, 43, 52, 82,  3, 28, 55, 49, 45, 63, 52, 27, 62, 44, 73,
      5, 55, 62, 20, 83, 53, 62, 83, 59, 38, 43, 18, 25, 63, 17, 11, 11, 26, 53, 10,
      8, 49, 63, 82, 14, 27, 61, 27, 49, 46, 62, 11, 74, 34, 17, 85, 62, 16, 44, 83,
     29, 49, 44, 27, 72,  3,  8,  8, 53, 37, 27, 52, 53,  5, 63, 59, 31, 27,  3, 49,
     27, 54, 17, 27,  5,  8, 27, 27, 27, 30, 44, 27, 63, 49,  5, 26, 72, 50, 73, 13,
     43, 49, 59, 25, 17, 63, 76, 44, 44, 44, 44, 27, 49, 52, 42,  3, 37, 50, 59, 20,
      8,  5, 52,  2, 53, 10, 45, 80, 49, 71, 11, 21, 62, 44, 56,  1, 27, 48, 13,  5,
     10, 27, 16, 49, 80, 62, 49, 11, 59, 62, 16, 73,  8, 20, 20, 49, 74, 62, 47, 53,
     43, 14,  9,  8,  5, 49, 49,
};

#endif /* TZ_TABLE_H */
