#!/usr/bin/env python3
"""
Generate tz_table.h for GPSDO FreeRTOS from the system IANA tzdata.
The IANA database ships each zone as a TZif file whose final line is the
POSIX TZ string describing the CURRENT rule -- which is all a GPSDO needs
(it shows the time now, not in 1895). That string is 4-44 bytes and encodes
the standard offset, the DST offset and both transition rules, including
half-hour offsets and southern-hemisphere ordering.

Run this when tzdata is updated:
  Linux/macOS: python3 gen_tz_table.py > tz_table.h
  Windows:     pip install tzdata && python gen_tz_table.py > tz_table.h
"""
import os, sys

def find_tz_base():
    """Znajduje ścieżkę do bazy IANA tzdata (Linux/macOS lub Windows pip)."""
    # 1. Standardowa ścieżka dla Linux/macOS
    linux_path = '/usr/share/zoneinfo'
    if os.path.isdir(linux_path):
        return linux_path
    
    # 2. Ścieżka dla Windows (z pakietu 'tzdata' instalowanego przez pip)
    try:
        import tzdata
        pip_path = os.path.join(os.path.dirname(tzdata.__file__), 'zoneinfo')
        if os.path.isdir(pip_path):
            return pip_path
    except ImportError:
        pass

    # 3. Opcjonalnie: ścieżka zdefiniowana w zmiennej środowiskowej
    env_path = os.environ.get('TZDATA_PATH')
    if env_path and os.path.isdir(env_path):
        return env_path

    return None

BASE = find_tz_base()
if not BASE:
    sys.exit("Cannot find IANA tzdata. On Windows, please run: pip install tzdata")

# Etc/* are GMT+N aliases with inverted signs -- confusing and pointless here.
# Right/ and posix/ are alternate encodings of the same zones.
SKIP_DIRS  = ('posix', 'right')
SKIP_PREFIX = ('Etc/',)

def collect():
    zones = []
    seen_cities = set() # Zamiast polegać na os.path.islink, śledzimy unikalne miasta
    
    # Sort both the directory descent and the file list so the walk order is
    # identical on every OS. Without this, os.walk follows filesystem order,
    # which differs between ext4/APFS/NTFS — and where two paths share a city
    # (Asia/Istanbul vs Europe/Istanbul, Asia/Nicosia vs Europe/Nicosia) the
    # seen_cities guard would then keep whichever the filesystem happened to
    # yield first, making the generated table platform-dependent.
    for root, dirs, files in os.walk(BASE):
        dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS)
        for f in sorted(files):
            p = os.path.join(root, f)
            
            # WAŻNE: Normalizacja separatorów ścieżek dla Windows (\ -> /)
            name = os.path.relpath(p, BASE).replace('\\', '/')
            
            if name.endswith(('.tab', '.list')) or '/' not in name:
                continue
            if name.startswith(SKIP_PREFIX):
                continue
                
            city = name.split('/')[-1]
            # Pomijamy aliasy (np. US/Eastern), które mają tę samą nazwę miasta
            if city in seen_cities:
                continue
            seen_cities.add(city)

            try:
                data = open(p, 'rb').read()
            except OSError:
                continue
                
            if not data.startswith(b'TZif'):
                continue
                
            # Naprawiono urwane b'\n' z oryginalnego kodu
            parts = data.split(b'\n')
            if len(parts) >= 2 and parts[-2]:
                zones.append((name, parts[-2].decode('ascii', 'ignore')))
    return zones

def main():
    zones = collect()
    if not zones:
        sys.exit("no zones found -- is tzdata installed?")
        
    # sort by city, case-folded: the lookup bisects on this order
    zones.sort(key=lambda z: z[0].split('/')[-1].lower())
    rules   = sorted({s for _, s in zones})
    regions = sorted({n.split('/')[0] for n, _ in zones})
    rule_id = {s: i for i, s in enumerate(rules)}
    reg_id  = {r: i for i, r in enumerate(regions)}
    
    if len(rules) > 255 or len(regions) > 255:
        sys.exit("rule/region count exceeds uint8_t")
        
    # The lookup bisects on the city name, so duplicates would make it
    # ambiguous and a sort/compare mismatch would make it plain wrong.
    cities = [n.split('/')[-1] for n, _ in zones]
    dup = {c for c in cities if cities.count(c) > 1}
    if dup:
        sys.exit(f"duplicate city names, lookup would be ambiguous: {sorted(dup)}")
    if cities != sorted(cities, key=str.lower):
        sys.exit("internal: table not sorted the way tz_lookup compares")
        
    # string blob: city names, NUL-separated, referenced by uint16 offset
    blob, offs = bytearray(), []
    for n, _ in zones:
        offs.append(len(blob))
        blob += n.split('/')[-1].encode('ascii') + b'\0'
        
    if len(blob) > 65535:
        sys.exit("string blob exceeds uint16 offset range")
        
    o = sys.stdout.write
    o("/* AUTO-GENERATED by tools/gen_tz_table.py -- do not edit.\n"
      " * Source: IANA tzdata via /usr/share/zoneinfo (or pip tzdata)\n"
      " * Regenerate when tzdata changes; see the script header. */\n")
    o("#ifndef TZ_TABLE_H\n"
      "#define TZ_TABLE_H\n"
      "#include <stdint.h>\n")
    o(f"#define TZ_NZONES   {len(zones)}\n")
    o(f"#define TZ_NRULES   {len(rules)}\n")
    o(f"#define TZ_NREGIONS {len(regions)}\n")
    
    o("/* POSIX TZ rule strings, deduplicated across zones. */\n")
    o("static const char *const tz_rule_str[TZ_NRULES] = {\n")
    for s in rules:
        o(f'    "{s}",\n')
    o("};\n")
    
    o("static const char *const tz_region_str[TZ_NREGIONS] = {\n")
    for r in regions:
        o(f'    "{r}",\n')
    o("};\n")
    
    o("/* City names, NUL-separated, sorted case-insensitively. */\n")
    o("static const char tz_city_blob[] =\n")
    line = ""
    for n, _ in zones:
        city = n.split('/')[-1]
        piece = f'"{city}\\0"'
        if len(line) + len(piece) > 72:
            o(f"    {line}\n"); line = ""
        line += piece
    if line:
        o(f"    {line}\n")
    o(";\n")
    
    o("static const uint16_t tz_city_off[TZ_NZONES] = {\n")
    for i in range(0, len(offs), 12):
        o("    " + ",".join(f"{x:5d}" for x in offs[i:i+12]) + ",\n")
    o("};\n")
    
    o("static const uint8_t tz_zone_region[TZ_NZONES] = {\n")
    ids = [reg_id[n.split('/')[0]] for n, _ in zones]
    for i in range(0, len(ids), 20):
        o("    " + ",".join(f"{x:3d}" for x in ids[i:i+20]) + ",\n")
    o("};\n")
    
    o("static const uint8_t tz_zone_rule[TZ_NZONES] = {\n")
    ids = [rule_id[s] for _, s in zones]
    for i in range(0, len(ids), 20):
        o("    " + ",".join(f"{x:3d}" for x in ids[i:i+20]) + ",\n")
    o("};\n")
    o("#endif /* TZ_TABLE_H */\n")
    
    sz = len(blob) + len(zones)*4 + sum(len(s)+1 for s in rules) + sum(len(r)+1 for r in regions)
    sys.stderr.write(f"zones={len(zones)} rules={len(rules)} regions={len(regions)}\n")
    sys.stderr.write(f"approx flash: {sz} B ({sz/1024:.1f} KB)\n")

if __name__ == '__main__':
    main()