/* AUTO-GENERATED by the GPSDO Tuner (Raw monitor tab) -- do not edit.
 * IANA release: 2026d
 * Generated:    2026-09-12 22:41:31
 * Zone data comes from this machine. To refresh it:
 *   pip install -U tzdata      (any OS; zic-compiled IANA data)
 * then press the button again. */
#ifndef GPSDO_TZ_TABLE_H
#define GPSDO_TZ_TABLE_H

#include <stdint.h>

#define TZ_NZONES   503
#define TZ_NRULES   88
#define TZ_NREGIONS 15

/* POSIX TZ rule strings, deduplicated across zones. */
static const char *const tz_rule_str[TZ_NRULES] = {
    "<+00>0",
    "<+00>0<+02>-2,M3.5.0/1,M10.5.0/3",
    "<+0330>-3:30",
    "<+03>-3",
    "<+0430>-4:30",
    "<+04>-4",
    "<+0530>-5:30",
    "<+0545>-5:45",
    "<+05>-5",
    "<+0630>-6:30",
    "<+06>-6",
    "<+07>-7",
    "<+0845>-8:45",
    "<+08>-8",
    "<+09>-9",
    "<+1030>-10:30<+11>-11,M10.1.0,M4.1.0",
    "<+10>-10",
    "<+11>-11",
    "<+11>-11<+12>,M10.1.0,M4.1.0/3",
    "<+1245>-12:45<+1345>,M9.5.0/2:45,M4.1.0/3:45",
    "<+12>-12",
    "<+13>-13",
    "<+14>-14",
    "<-01>1",
    "<-01>1<+00>,M3.5.0/0,M10.5.0/1",
    "<-02>2",
    "<-02>2<-01>,M3.5.0/-1,M10.5.0/0",
    "<-03>3",
    "<-03>3<-02>,M3.2.0,M11.1.0",
    "<-04>4",
    "<-04>4<-03>,M9.1.6/24,M4.1.6/24",
    "<-05>5",
    "<-06>6",
    "<-06>6<-05>,M9.1.6/22,M4.1.6/22",
    "<-08>8",
    "<-0930>9:30",
    "<-09>9",
    "<-10>10",
    "<-11>11",
    "ACST-9:30",
    "ACST-9:30ACDT,M10.1.0,M4.1.0/3",
    "AEST-10",
    "AEST-10AEDT,M10.1.0,M4.1.0/3",
    "AKST9AKDT,M3.2.0,M11.1.0",
    "AST4",
    "AST4ADT,M3.2.0,M11.1.0",
    "AWST-8",
    "CAT-2",
    "CET-1",
    "CET-1CEST,M3.5.0,M10.5.0/3",
    "CST-8",
    "CST5CDT,M3.2.0/0,M11.1.0/1",
    "CST6",
    "CST6CDT,M3.2.0,M11.1.0",
    "ChST-10",
    "EAT-3",
    "EET-2",
    "EET-2EEST,M3.4.4/50,M10.4.4/50",
    "EET-2EEST,M3.5.0/0,M10.5.0/0",
    "EET-2EEST,M3.5.0/3,M10.5.0/4",
    "EET-2EEST,M4.5.5/0,M10.5.4/24",
    "EST5",
    "EST5EDT,M3.2.0,M11.1.0",
    "GMT0",
    "GMT0BST,M3.5.0/1,M10.5.0",
    "HKT-8",
    "HST10",
    "HST10HDT,M3.2.0,M11.1.0",
    "IST-1GMT0,M10.5.0,M3.5.0/1",
    "IST-2IDT,M3.4.4/26,M10.5.0",
    "IST-5:30",
    "JST-9",
    "KST-9",
    "MSK-3",
    "MST7",
    "MST7MDT,M3.2.0,M11.1.0",
    "NST3:30NDT,M3.2.0,M11.1.0",
    "NZST-12NZDT,M9.5.0,M4.1.0/3",
    "PKT-5",
    "PST-8",
    "PST8PDT,M3.2.0,M11.1.0",
    "SAST-2",
    "SST11",
    "WAT-1",
    "WET0WEST,M3.5.0/1,M10.5.0",
    "WIB-7",
    "WIT-9",
    "WITA-8",
};

static const char *const tz_region_str[TZ_NREGIONS] = {
    "Africa",
    "America",
    "Antarctica",
    "Arctic",
    "Asia",
    "Atlantic",
    "Australia",
    "Brazil",
    "Canada",
    "Chile",
    "Europe",
    "Indian",
    "Mexico",
    "Pacific",
    "US",
};

/* City names, NUL-separated, sorted case-insensitively. */
static const char tz_city_blob[] =
    "Abidjan\0""Accra\0""Acre\0""ACT\0""Adak\0""Addis_Ababa\0""Adelaide\0"
    "Aden\0""Alaska\0""Aleutian\0""Algiers\0""Almaty\0""Amman\0"
    "Amsterdam\0""Anadyr\0""Anchorage\0""Andorra\0""Anguilla\0"
    "Antananarivo\0""Antigua\0""Apia\0""Aqtau\0""Aqtobe\0""Araguaina\0"
    "Arizona\0""Aruba\0""Ashgabat\0""Ashkhabad\0""Asmara\0""Asmera\0"
    "Astrakhan\0""Asuncion\0""Athens\0""Atikokan\0""Atka\0""Atlantic\0"
    "Atyrau\0""Auckland\0""Azores\0""Baghdad\0""Bahia\0""Bahia_Banderas\0"
    "Bahrain\0""BajaNorte\0""BajaSur\0""Baku\0""Bamako\0""Bangkok\0"
    "Bangui\0""Banjul\0""Barbados\0""Barnaul\0""Beirut\0""Belem\0"
    "Belfast\0""Belgrade\0""Belize\0""Berlin\0""Bermuda\0""Beulah\0"
    "Bishkek\0""Bissau\0""Blanc-Sablon\0""Blantyre\0""Boa_Vista\0""Bogota\0"
    "Boise\0""Bougainville\0""Bratislava\0""Brazzaville\0""Brisbane\0"
    "Broken_Hill\0""Brunei\0""Brussels\0""Bucharest\0""Budapest\0"
    "Buenos_Aires\0""Bujumbura\0""Busingen\0""Cairo\0""Calcutta\0"
    "Cambridge_Bay\0""Campo_Grande\0""Canary\0""Canberra\0""Cancun\0"
    "Cape_Verde\0""Caracas\0""Casablanca\0""Casey\0""Catamarca\0""Cayenne\0"
    "Cayman\0""Center\0""Central\0""Ceuta\0""Chagos\0""Chatham\0""Chicago\0"
    "Chihuahua\0""Chisinau\0""Chita\0""Choibalsan\0""Chongqing\0"
    "Christmas\0""Chungking\0""Chuuk\0""Ciudad_Juarez\0""Cocos\0""Colombo\0"
    "ComodRivadavia\0""Comoro\0""Conakry\0""Continental\0""Copenhagen\0"
    "Coral_Harbour\0""Cordoba\0""Costa_Rica\0""Coyhaique\0""Creston\0"
    "Cuiaba\0""Curacao\0""Currie\0""Dacca\0""Dakar\0""Damascus\0"
    "Danmarkshavn\0""Dar_es_Salaam\0""Darwin\0""Davis\0""Dawson\0"
    "Dawson_Creek\0""DeNoronha\0""Denver\0""Detroit\0""Dhaka\0""Dili\0"
    "Djibouti\0""Dominica\0""Douala\0""Dubai\0""Dublin\0""DumontDUrville\0"
    "Dushanbe\0""East\0""East-Indiana\0""Easter\0""EasterIsland\0"
    "Eastern\0""Edmonton\0""Efate\0""Eirunepe\0""El_Aaiun\0""El_Salvador\0"
    "Enderbury\0""Ensenada\0""Eucla\0""Faeroe\0""Fakaofo\0""Famagusta\0"
    "Faroe\0""Fiji\0""Fort_Nelson\0""Fort_Wayne\0""Fortaleza\0""Freetown\0"
    "Funafuti\0""Gaborone\0""Galapagos\0""Gambier\0""Gaza\0""General\0"
    "Gibraltar\0""Glace_Bay\0""Godthab\0""Goose_Bay\0""Grand_Turk\0"
    "Grenada\0""Guadalcanal\0""Guadeloupe\0""Guam\0""Guatemala\0"
    "Guayaquil\0""Guernsey\0""Guyana\0""Halifax\0""Harare\0""Harbin\0"
    "Havana\0""Hawaii\0""Hebron\0""Helsinki\0""Hermosillo\0""Ho_Chi_Minh\0"
    "Hobart\0""Hong_Kong\0""Honolulu\0""Hovd\0""Indiana-Starke\0"
    "Indianapolis\0""Inuvik\0""Iqaluit\0""Irkutsk\0""Isle_of_Man\0"
    "Istanbul\0""Jakarta\0""Jamaica\0""Jan_Mayen\0""Jayapura\0""Jersey\0"
    "Jerusalem\0""Johannesburg\0""Johnston\0""Juba\0""Jujuy\0""Juneau\0"
    "Kabul\0""Kaliningrad\0""Kamchatka\0""Kampala\0""Kanton\0""Karachi\0"
    "Kashgar\0""Kathmandu\0""Katmandu\0""Kerguelen\0""Khandyga\0"
    "Khartoum\0""Kiev\0""Kigali\0""Kinshasa\0""Kiritimati\0""Kirov\0"
    "Knox\0""Knox_IN\0""Kolkata\0""Kosrae\0""Kralendijk\0""Krasnoyarsk\0"
    "Kuala_Lumpur\0""Kuching\0""Kuwait\0""Kwajalein\0""Kyiv\0""La_Paz\0"
    "La_Rioja\0""Lagos\0""LHI\0""Libreville\0""Lima\0""Lindeman\0""Lisbon\0"
    "Ljubljana\0""Lome\0""London\0""Longyearbyen\0""Lord_Howe\0"
    "Los_Angeles\0""Louisville\0""Lower_Princes\0""Luanda\0""Lubumbashi\0"
    "Lusaka\0""Luxembourg\0""Macao\0""Macau\0""Maceio\0""Macquarie\0"
    "Madeira\0""Madrid\0""Magadan\0""Mahe\0""Majuro\0""Makassar\0""Malabo\0"
    "Maldives\0""Malta\0""Managua\0""Manaus\0""Manila\0""Maputo\0"
    "Marengo\0""Mariehamn\0""Marigot\0""Marquesas\0""Martinique\0""Maseru\0"
    "Matamoros\0""Mauritius\0""Mawson\0""Mayotte\0""Mazatlan\0""Mbabane\0"
    "McMurdo\0""Melbourne\0""Mendoza\0""Menominee\0""Merida\0""Metlakatla\0"
    "Mexico_City\0""Michigan\0""Midway\0""Minsk\0""Miquelon\0""Mogadishu\0"
    "Monaco\0""Moncton\0""Monrovia\0""Monterrey\0""Montevideo\0"
    "Monticello\0""Montreal\0""Montserrat\0""Moscow\0""Mountain\0""Muscat\0"
    "Nairobi\0""Nassau\0""Nauru\0""Ndjamena\0""New_Salem\0""New_York\0"
    "Newfoundland\0""Niamey\0""Nicosia\0""Nipigon\0""Niue\0""Nome\0"
    "Norfolk\0""Noronha\0""North\0""Nouakchott\0""Noumea\0""Novokuznetsk\0"
    "Novosibirsk\0""NSW\0""Nuuk\0""Ojinaga\0""Omsk\0""Oral\0""Oslo\0"
    "Ouagadougou\0""Pacific\0""Pago_Pago\0""Palau\0""Palmer\0""Panama\0"
    "Pangnirtung\0""Paramaribo\0""Paris\0""Perth\0""Petersburg\0"
    "Phnom_Penh\0""Phoenix\0""Pitcairn\0""Podgorica\0""Pohnpei\0""Ponape\0"
    "Pontianak\0""Port-au-Prince\0""Port_Moresby\0""Port_of_Spain\0"
    "Porto-Novo\0""Porto_Acre\0""Porto_Velho\0""Prague\0""Puerto_Rico\0"
    "Punta_Arenas\0""Pyongyang\0""Qatar\0""Qostanay\0""Queensland\0"
    "Qyzylorda\0""Rainy_River\0""Rangoon\0""Rankin_Inlet\0""Rarotonga\0"
    "Recife\0""Regina\0""Resolute\0""Reunion\0""Reykjavik\0""Riga\0"
    "Rio_Branco\0""Rio_Gallegos\0""Riyadh\0""Rome\0""Rosario\0""Rothera\0"
    "Saigon\0""Saipan\0""Sakhalin\0""Salta\0""Samara\0""Samarkand\0"
    "Samoa\0""San_Juan\0""San_Luis\0""San_Marino\0""Santa_Isabel\0"
    "Santarem\0""Santiago\0""Santo_Domingo\0""Sao_Paulo\0""Sao_Tome\0"
    "Sarajevo\0""Saratov\0""Saskatchewan\0""Scoresbysund\0""Seoul\0"
    "Shanghai\0""Shiprock\0""Simferopol\0""Singapore\0""Sitka\0""Skopje\0"
    "Sofia\0""South\0""South_Georgia\0""South_Pole\0""Srednekolymsk\0"
    "St_Barthelemy\0""St_Helena\0""St_Johns\0""St_Kitts\0""St_Lucia\0"
    "St_Thomas\0""St_Vincent\0""Stanley\0""Stockholm\0""Swift_Current\0"
    "Sydney\0""Syowa\0""Tahiti\0""Taipei\0""Tallinn\0""Tarawa\0""Tashkent\0"
    "Tasmania\0""Tbilisi\0""Tegucigalpa\0""Tehran\0""Tel_Aviv\0"
    "Tell_City\0""Thimbu\0""Thimphu\0""Thule\0""Thunder_Bay\0""Tijuana\0"
    "Timbuktu\0""Tirane\0""Tiraspol\0""Tokyo\0""Tomsk\0""Tongatapu\0"
    "Toronto\0""Tortola\0""Tripoli\0""Troll\0""Truk\0""Tucuman\0""Tunis\0"
    "Ujung_Pandang\0""Ulaanbaatar\0""Ulan_Bator\0""Ulyanovsk\0""Urumqi\0"
    "Ushuaia\0""Ust-Nera\0""Uzhgorod\0""Vaduz\0""Vancouver\0""Vatican\0"
    "Vevay\0""Victoria\0""Vienna\0""Vientiane\0""Vilnius\0""Vincennes\0"
    "Virgin\0""Vladivostok\0""Volgograd\0""Vostok\0""Wake\0""Wallis\0"
    "Warsaw\0""West\0""Whitehorse\0""Winamac\0""Windhoek\0""Winnipeg\0"
    "Yakutat\0""Yakutsk\0""Yancowinna\0""Yangon\0""Yap\0""Yekaterinburg\0"
    "Yellowknife\0""Yerevan\0""Yukon\0""Zagreb\0""Zaporozhye\0""Zurich\0"
;

static const uint16_t tz_city_off[TZ_NZONES] = {
        0,    8,   14,   19,   23,   28,   40,   49,   54,   61,   70,   78,
       85,   91,  101,  108,  118,  126,  135,  148,  156,  161,  167,  174,
      184,  192,  198,  207,  217,  224,  231,  241,  250,  257,  266,  271,
      280,  287,  296,  303,  311,  317,  332,  340,  350,  358,  363,  370,
      378,  385,  392,  401,  409,  416,  422,  430,  439,  446,  453,  461,
      468,  476,  483,  496,  505,  515,  522,  528,  541,  552,  564,  573,
      585,  592,  601,  611,  620,  633,  643,  652,  658,  667,  681,  694,
      701,  710,  717,  728,  736,  747,  753,  763,  771,  778,  785,  793,
      799,  806,  814,  822,  832,  841,  847,  858,  868,  878,  888,  894,
      908,  914,  922,  937,  944,  952,  964,  975,  989,  997, 1008, 1018,
     1026, 1033, 1041, 1048, 1054, 1060, 1069, 1082, 1096, 1103, 1109, 1116,
     1129, 1139, 1146, 1154, 1160, 1165, 1174, 1183, 1190, 1196, 1203, 1218,
     1227, 1232, 1245, 1252, 1265, 1273, 1282, 1288, 1297, 1306, 1318, 1328,
     1337, 1343, 1350, 1358, 1368, 1374, 1379, 1391, 1402, 1412, 1421, 1430,
     1439, 1449, 1457, 1462, 1470, 1480, 1490, 1498, 1508, 1519, 1527, 1539,
     1550, 1555, 1565, 1575, 1584, 1591, 1599, 1606, 1613, 1620, 1627, 1634,
     1643, 1654, 1666, 1673, 1683, 1692, 1697, 1712, 1725, 1732, 1740, 1748,
     1760, 1769, 1777, 1785, 1795, 1804, 1811, 1821, 1834, 1843, 1848, 1854,
     1861, 1867, 1879, 1889, 1897, 1904, 1912, 1920, 1930, 1939, 1949, 1958,
     1967, 1972, 1979, 1988, 1999, 2005, 2010, 2018, 2026, 2033, 2044, 2056,
     2069, 2077, 2084, 2094, 2099, 2106, 2115, 2121, 2125, 2136, 2141, 2150,
     2157, 2167, 2172, 2179, 2192, 2202, 2214, 2225, 2239, 2246, 2257, 2264,
     2275, 2281, 2287, 2294, 2304, 2312, 2319, 2327, 2332, 2339, 2348, 2355,
     2364, 2370, 2378, 2385, 2392, 2399, 2407, 2417, 2425, 2435, 2446, 2453,
     2463, 2473, 2480, 2488, 2497, 2505, 2513, 2523, 2531, 2541, 2548, 2559,
     2571, 2580, 2587, 2593, 2602, 2612, 2619, 2627, 2636, 2646, 2657, 2668,
     2677, 2688, 2695, 2704, 2711, 2719, 2726, 2732, 2741, 2751, 2760, 2773,
     2780, 2788, 2796, 2801, 2806, 2814, 2822, 2828, 2839, 2846, 2859, 2871,
     2875, 2880, 2888, 2893, 2898, 2903, 2915, 2923, 2933, 2939, 2946, 2953,
     2965, 2976, 2982, 2988, 2999, 3010, 3018, 3027, 3037, 3045, 3052, 3062,
     3077, 3090, 3104, 3115, 3126, 3138, 3145, 3157, 3170, 3180, 3186, 3195,
     3206, 3216, 3228, 3236, 3249, 3259, 3266, 3273, 3282, 3290, 3300, 3305,
     3316, 3329, 3336, 3341, 3349, 3357, 3364, 3371, 3380, 3386, 3393, 3403,
     3409, 3418, 3427, 3438, 3451, 3460, 3469, 3483, 3493, 3502, 3511, 3519,
     3532, 3545, 3551, 3560, 3569, 3580, 3590, 3596, 3603, 3609, 3615, 3629,
     3640, 3654, 3668, 3678, 3687, 3696, 3705, 3715, 3726, 3734, 3744, 3758,
     3765, 3771, 3778, 3785, 3793, 3800, 3809, 3818, 3826, 3838, 3845, 3854,
     3864, 3871, 3879, 3885, 3897, 3905, 3914, 3921, 3930, 3936, 3942, 3952,
     3960, 3968, 3976, 3982, 3987, 3995, 4001, 4015, 4027, 4038, 4048, 4055,
     4063, 4072, 4081, 4087, 4097, 4105, 4111, 4120, 4127, 4137, 4145, 4155,
     4162, 4174, 4184, 4191, 4196, 4203, 4210, 4215, 4226, 4234, 4243, 4252,
     4260, 4268, 4279, 4286, 4290, 4304, 4316, 4324, 4330, 4337, 4348,
};

static const uint8_t tz_zone_region[TZ_NZONES] = {
      0,  0,  7,  6,  1,  0,  6,  4, 14, 14,  0,  4,  4, 10,  4,  1, 10,  1, 11,  1,
     13,  4,  4,  1, 14,  1,  4,  4,  0,  0, 10,  1, 10,  1,  1,  8,  4, 13,  5,  4,
      1,  1,  4, 12, 12,  4,  0,  4,  0,  0,  1,  4,  4,  1, 10, 10,  1, 10,  5,  1,
      4,  0,  1,  0,  1,  1,  1, 13, 10,  0,  6,  6,  4, 10, 10, 10,  1,  0, 10,  0,
      4,  1,  1,  5,  6,  1,  5,  1,  0,  2,  1,  1,  1,  1,  8,  0, 11, 13,  1,  1,
     10,  4,  4,  4, 11,  4, 13,  1, 11,  4,  1, 11,  0,  9, 10,  1,  1,  1,  1,  1,
      1,  1,  6,  4,  0,  4,  1,  0,  6,  2,  1,  1,  7,  1,  1,  4,  4,  0,  1,  0,
      4, 10,  2,  4,  7, 14, 13,  9,  8,  1, 13,  1,  0,  1, 13,  1,  6,  5, 13,  4,
      5, 13,  1,  1,  1,  0, 13,  0, 13, 13,  4, 12, 10,  1,  1,  1,  1,  1, 13,  1,
     13,  1,  1, 10,  1,  1,  0,  4,  1, 14,  4, 10,  1,  4,  6,  4, 13,  4, 14,  1,
      1,  1,  4, 10,  4,  4,  1,  5,  4, 10,  4,  0, 13,  0,  1,  1,  4, 10,  4,  0,
     13,  4,  4,  4,  4, 11,  4,  0, 10,  0,  0, 13, 10,  1,  1,  4, 13,  1,  4,  4,
      4,  4, 13, 10,  1,  1,  0,  6,  0,  1,  6, 10, 10,  0, 10,  3,  6,  1,  1,  1,
      0,  0,  0, 10,  4,  4,  1,  2,  5, 10,  4, 11, 13,  4,  0, 11, 10,  1,  1,  4,
      0,  1, 10,  1, 13,  1,  0,  1, 11,  2, 11,  1,  0,  2,  6,  1,  1,  1,  1,  1,
     14, 13, 10,  1,  0, 10,  1,  0,  1,  1,  1,  1,  1, 10,  8,  4,  0,  1, 13,  0,
      1,  1,  8,  0,  4,  1, 13,  1, 13,  1,  6,  0, 13,  4,  4,  6,  1,  1,  4,  4,
     10,  0,  8, 13, 13,  2,  1,  1,  1, 10,  6,  1,  4,  1, 13, 10, 13, 13,  4,  1,
     13,  1,  0,  1,  1, 10,  1,  1,  4,  4,  4,  6,  4,  1,  4,  1, 13,  1,  1,  1,
     11,  5, 10,  1,  1,  4, 10,  1,  2,  4, 13,  4,  1, 10,  4, 13,  1,  1, 10,  1,
      1,  1,  1,  1,  0, 10, 10,  8,  1,  4,  4,  1, 10,  4,  1, 10, 10,  6,  5,  2,
      4,  1,  5,  1,  1,  1,  1,  1,  5, 10,  1,  6,  2, 13,  4, 10, 13,  4,  6,  4,
      1,  4,  4,  1,  4,  4,  1,  1,  1,  0, 10, 10,  4,  4, 13,  1,  1,  0,  2, 13,
      1,  0,  4,  4,  4, 10,  4,  1,  4, 10, 10,  1, 10,  1,  6, 10,  4, 10,  1,  1,
      4, 10,  2, 13, 13, 10,  6,  1,  1,  0,  1,  1,  4,  6,  4, 13,  4,  1,  4,  8,
     10, 10, 10,
};

static const uint8_t tz_zone_rule[TZ_NZONES] = {
     63, 63, 31, 42, 67, 55, 40,  3, 43, 67, 48,  8,  3, 49, 20, 43, 49, 44, 55, 44,
     21,  8,  8, 27, 74, 44,  8,  8, 55, 55,  5, 27, 59, 61, 67, 45,  8, 77, 24,  3,
     27, 52,  3, 80, 74,  5, 63, 11, 83, 63, 44, 11, 58, 27, 64, 49, 52, 49, 45, 53,
     10, 63, 44, 47, 29, 31, 75, 17, 49, 83, 41, 40, 13, 49, 59, 49, 27, 47, 49, 60,
     70, 75, 29, 84, 42, 61, 23, 29,  0, 13, 27, 27, 61, 53, 53, 49, 10, 19, 53, 52,
     59, 14, 13, 50, 11, 50, 16, 75,  9,  6, 27, 55, 63, 30, 49, 61, 27, 52, 27, 74,
     29, 44, 42, 10, 63,  3, 63, 55, 39, 11, 74, 74, 25, 75, 62, 10, 14, 55, 44, 83,
      5, 68, 16,  8, 27, 62, 33, 33, 62, 52, 17, 31,  0, 52, 21, 80, 12, 84, 21, 59,
     84, 20, 74, 62, 27, 63, 20, 47, 32, 36, 57, 52, 49, 45, 26, 45, 62, 44, 17, 44,
     54, 52, 31, 64, 29, 45, 47, 50, 51, 66, 57, 59, 74, 11, 42, 65, 66, 11, 53, 62,
     52, 62, 13, 64,  3, 85, 61, 49, 86, 64, 69, 81, 66, 47, 27, 43,  4, 56, 20, 55,
     21, 78, 10,  7,  7,  8, 14, 47, 59, 47, 83, 22, 73, 53, 53, 70, 17, 44, 11, 13,
     13,  3, 20, 59, 29, 27, 83, 15, 83, 31, 41, 84, 49, 63, 64, 49, 15, 80, 62, 44,
     83, 47, 47, 49, 50, 50, 27, 42, 84, 49, 17,  5, 20, 87, 83,  8, 49, 52, 29, 79,
     47, 62, 59, 44, 35, 44, 81, 53,  5,  8, 55, 74, 81, 77, 42, 27, 53, 52, 43, 52,
     62, 82,  3, 28, 55, 49, 45, 63, 52, 27, 62, 62, 44, 73, 52,  5, 55, 62, 20, 83,
     53, 62, 76, 83, 59, 62, 38, 43, 18, 25, 39, 63, 17, 11, 11, 42, 26, 53, 10,  8,
     49, 63, 74, 82, 14, 27, 61, 62, 27, 49, 46, 62, 11, 74, 34, 49, 17, 17, 85, 62,
     16, 44, 83, 31, 29, 49, 44, 27, 72,  3,  8, 41,  8, 53,  9, 53, 37, 27, 52, 53,
      5, 63, 59, 31, 27,  3, 49, 27, 27, 11, 54, 17, 27,  5,  8, 82, 27, 27, 49, 80,
     27, 30, 44, 27, 63, 49,  5, 52, 26, 72, 50, 75, 73, 13, 43, 49, 59, 40, 25, 77,
     17, 44, 63, 76, 44, 44, 44, 44, 27, 49, 52, 42,  3, 37, 50, 59, 20,  8, 42,  5,
     52,  2, 69, 53, 10, 10, 45, 62, 80, 63, 49, 59, 71, 11, 21, 62, 44, 56,  1, 16,
     27, 48, 87, 13, 13,  5, 10, 27, 16, 59, 49, 74, 49, 62, 42, 49, 11, 59, 62, 44,
     16, 73,  8, 20, 20, 49, 46, 74, 62, 47, 53, 43, 14, 40,  9, 16,  8, 52,  5, 74,
     49, 59, 49,
};

#endif /* GPSDO_TZ_TABLE_H */
